name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential g++

    - name: Build project
      run: |
        g++ -std=c++17 -o bank_app main.cpp Account.cpp Transaction.cpp Bank.cpp

    - name: Create expected output files
      run: |
        echo -e "=== Banking System Menu ===\n1. Create Account\n2. Deposit\n3. Withdraw\n4. Transfer\n5. View All Accounts\n6. View Transaction History\n7. View Account Transactions\n8. Exit\nEnter choice: Account created successfully!\n=== Banking System Menu ===\n1. Create Account\n2. Deposit\n3. Withdraw\n4. Transfer\n5. View All Accounts\n6. View Transaction History\n7. View Account Transactions\n8. Exit\nEnter choice: " > expected_output_test1.txt
        
        echo -e "=== Banking System Menu ===\n1. Create Account\n2. Deposit\n3. Withdraw\n4. Transfer\n5. View All Accounts\n6. View Transaction History\n7. View Account Transactions\n8. Exit\nEnter choice: Deposit successful!\n=== Banking System Menu ===\n1. Create Account\n2. Deposit\n3. Withdraw\n4. Transfer\n5. View All Accounts\n6. View Transaction History\n7. View Account Transactions\n8. Exit\nEnter choice: " > expected_output_test2.txt

    - name: Run tests with detailed logging
      run: |
        # Test 1: Create Account
        echo "Running Test 1: Create Account"
        echo -e "1\nTEST001\nTest User\n1000\nSavings\n8" | ./bank_app > output_test1.txt
        if ! diff -q output_test1.txt expected_output_test1.txt; then
          echo "::error::Test 1 Failed - Create Account"
          echo "=== Expected Output ==="
          cat expected_output_test1.txt
          echo "=== Actual Output ==="
          cat output_test1.txt
          exit 1
        fi

        # Test 2: Deposit
        echo "Running Test 2: Deposit"
        echo -e "1\nTEST002\nTest User\n1000\nSavings\n2\nTEST002\n500\n8" | ./bank_app > output_test2.txt
        if ! diff -q output_test2.txt expected_output_test2.txt; then
          echo "::error::Test 2 Failed - Deposit"
          echo "=== Expected Output ==="
          cat expected_output_test2.txt
          echo "=== Actual Output ==="
          cat output_test2.txt
          exit 1
        fi

        # Test 3: Withdraw
        echo "Running Test 3: Withdraw"
        echo -e "1\nTEST003\nTest User\n1000\nSavings\n3\nTEST003\n200\n8" | ./bank_app > output_test3.txt
        if ! grep -q "Withdrawal successful!" output_test3.txt; then
          echo "::error::Test 3 Failed - Withdraw"
          echo "=== Actual Output ==="
          cat output_test3.txt
          exit 1
        fi

        # Test 4: Transfer
        echo "Running Test 4: Transfer"
        echo -e "1\nTEST004A\nSender\n1000\nSavings\n1\nTEST004B\nReceiver\n500\nSavings\n4\nTEST004A\nTEST004B\n300\n8" | ./bank_app > output_test4.txt
        if ! grep -q "Transfer successful!" output_test4.txt; then
          echo "::error::Test 4 Failed - Transfer"
          echo "=== Actual Output ==="
          cat output_test4.txt
          exit 1
        fi

        # Test 5: View All Accounts
        echo "Running Test 5: View All Accounts"
        echo -e "1\nTEST005\nTest User\n1000\nSavings\n5\n8" | ./bank_app > output_test5.txt
        if ! grep -q "TEST005" output_test5.txt; then
          echo "::error::Test 5 Failed - View All Accounts"
          echo "=== Actual Output ==="
          cat output_test5.txt
          exit 1
        fi

        # Test 6: View Transaction History
        echo "Running Test 6: View Transaction History"
        echo -e "1\nTEST006\nTest User\n1000\nSavings\n2\nTEST006\n500\n6\n8" | ./bank_app > output_test6.txt
        if ! grep -q "DEPOSIT" output_test6.txt; then
          echo "::error::Test 6 Failed - View Transaction History"
          echo "=== Actual Output ==="
          cat output_test6.txt
          exit 1
        fi

        # Test 7: View Account Transactions
        echo "Running Test 7: View Account Transactions"
        echo -e "1\nTEST007\nTest User\n1000\nSavings\n2\nTEST007\n500\n7\nTEST007\n8" | ./bank_app > output_test7.txt
        if ! grep -q "TEST007" output_test7.txt; then
          echo "::error::Test 7 Failed - View Account Transactions"
          echo "=== Actual Output ==="
          cat output_test7.txt
          exit 1
        fi

        # Test 8: Exit
        echo "Running Test 8: Exit"
        echo -e "8" | ./bank_app > output_test8.txt
        if [ -s output_test8.txt ]; then
          echo "::error::Test 8 Failed - Exit"
          echo "=== Actual Output ==="
          cat output_test8.txt
          exit 1
        fi
